//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputSystem/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""OnGround"",
            ""id"": ""31b00f99-5d8d-4a06-b02d-079223a5c161"",
            ""actions"": [
                {
                    ""name"": ""Movimento"",
                    ""type"": ""Value"",
                    ""id"": ""d7a24c57-6bb6-400d-beff-915b14c01452"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pulo"",
                    ""type"": ""Button"",
                    ""id"": ""aa2fd804-9726-45fb-9ec3-f29db1078d43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Visão"",
                    ""type"": ""Value"",
                    ""id"": ""f33b3485-ae61-42b3-a1ac-e503305802f8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Correr"",
                    ""type"": ""PassThrough"",
                    ""id"": ""75bbc331-094c-42de-b996-55d4676adf4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Agachar"",
                    ""type"": ""Button"",
                    ""id"": ""af7c816a-b57f-4dbc-ac27-fc74a41108f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Teclado"",
                    ""id"": ""47ab9ec4-b5fe-40e5-8868-5b9ca7082d53"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5b019859-7d63-40df-ac80-c1139e2efc0c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""894edadc-eb98-468d-bcaa-f8a2b856e455"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4375b020-b595-4efc-95ba-dcee2ed8a4c6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c2566bec-da9f-477f-8efb-b02b98775efc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4d7b0aeb-ed91-4af9-9686-f6c63c9f0004"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pulo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34bfb9ba-fe18-44ca-af6d-942138de2736"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pulo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1be2bb23-64eb-4b9b-af8a-d703684a799d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Visão"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""6c56b48f-21d7-4a2c-85a2-63d7738112d3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4488ca1d-9547-4aed-a13f-7aa9f95c7a0a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cccd46da-6fd8-4f61-a398-fbc920bbe653"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ed813e39-15f0-4b74-8465-c05ab3bcfac1"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a612b4f6-c137-41d7-a184-5a429e2dac0d"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fc7ed50c-132e-4d0d-9f93-d0aa7d173150"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Visão"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfa4630e-2c3a-48e1-b707-31597be5d24d"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b337cf57-e8f3-4b0e-bf5f-ff3ab1b1147f"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7011f3aa-28e5-4b78-9257-a34d9c4c8973"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agachar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51ed13b9-f2a4-4b58-9379-1e001178877b"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agachar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnGround
        m_OnGround = asset.FindActionMap("OnGround", throwIfNotFound: true);
        m_OnGround_Movimento = m_OnGround.FindAction("Movimento", throwIfNotFound: true);
        m_OnGround_Pulo = m_OnGround.FindAction("Pulo", throwIfNotFound: true);
        m_OnGround_Visão = m_OnGround.FindAction("Visão", throwIfNotFound: true);
        m_OnGround_Correr = m_OnGround.FindAction("Correr", throwIfNotFound: true);
        m_OnGround_Agachar = m_OnGround.FindAction("Agachar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnGround
    private readonly InputActionMap m_OnGround;
    private IOnGroundActions m_OnGroundActionsCallbackInterface;
    private readonly InputAction m_OnGround_Movimento;
    private readonly InputAction m_OnGround_Pulo;
    private readonly InputAction m_OnGround_Visão;
    private readonly InputAction m_OnGround_Correr;
    private readonly InputAction m_OnGround_Agachar;
    public struct OnGroundActions
    {
        private @PlayerInput m_Wrapper;
        public OnGroundActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimento => m_Wrapper.m_OnGround_Movimento;
        public InputAction @Pulo => m_Wrapper.m_OnGround_Pulo;
        public InputAction @Visão => m_Wrapper.m_OnGround_Visão;
        public InputAction @Correr => m_Wrapper.m_OnGround_Correr;
        public InputAction @Agachar => m_Wrapper.m_OnGround_Agachar;
        public InputActionMap Get() { return m_Wrapper.m_OnGround; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnGroundActions set) { return set.Get(); }
        public void SetCallbacks(IOnGroundActions instance)
        {
            if (m_Wrapper.m_OnGroundActionsCallbackInterface != null)
            {
                @Movimento.started -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnMovimento;
                @Movimento.performed -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnMovimento;
                @Movimento.canceled -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnMovimento;
                @Pulo.started -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnPulo;
                @Pulo.performed -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnPulo;
                @Pulo.canceled -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnPulo;
                @Visão.started -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnVisão;
                @Visão.performed -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnVisão;
                @Visão.canceled -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnVisão;
                @Correr.started -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnCorrer;
                @Correr.performed -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnCorrer;
                @Correr.canceled -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnCorrer;
                @Agachar.started -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnAgachar;
                @Agachar.performed -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnAgachar;
                @Agachar.canceled -= m_Wrapper.m_OnGroundActionsCallbackInterface.OnAgachar;
            }
            m_Wrapper.m_OnGroundActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movimento.started += instance.OnMovimento;
                @Movimento.performed += instance.OnMovimento;
                @Movimento.canceled += instance.OnMovimento;
                @Pulo.started += instance.OnPulo;
                @Pulo.performed += instance.OnPulo;
                @Pulo.canceled += instance.OnPulo;
                @Visão.started += instance.OnVisão;
                @Visão.performed += instance.OnVisão;
                @Visão.canceled += instance.OnVisão;
                @Correr.started += instance.OnCorrer;
                @Correr.performed += instance.OnCorrer;
                @Correr.canceled += instance.OnCorrer;
                @Agachar.started += instance.OnAgachar;
                @Agachar.performed += instance.OnAgachar;
                @Agachar.canceled += instance.OnAgachar;
            }
        }
    }
    public OnGroundActions @OnGround => new OnGroundActions(this);
    public interface IOnGroundActions
    {
        void OnMovimento(InputAction.CallbackContext context);
        void OnPulo(InputAction.CallbackContext context);
        void OnVisão(InputAction.CallbackContext context);
        void OnCorrer(InputAction.CallbackContext context);
        void OnAgachar(InputAction.CallbackContext context);
    }
}
